apiVersion: v2
appVersion: "0.0.1"
description: Component test chart for h2agent
name: ct-h2agent
version: "1.0"

dependencies:
  - name: h2agent
    version: 1.0.0
    repository: file://../h2agent
    alias: h2agent
