test:
  name: test
  replicaCount: 1
  image:
    repository: ghcr.io/testillano/ct-h2agent
    pullPolicy: IfNotPresent
    tag: latest
  podAnnotations:
    sidecar.istio.io/inject: "true"
  resources: {}

initContainer:
  image:
    repository: busybox
    pullPolicy: IfNotPresent
    tag: latest

h2agent:
  h2agent_cl:
    #log_level: Debug
    verbose:
      enabled: true
    remote_servers_lazy_connection:
      enabled: true
