ARG base_tag=latest
FROM ghcr.io/testillano/h2agent_builder:${base_tag}
LABEL maintainer="testillano"

LABEL testillano.h2agent.description="Docker image for h2agent UT coverage"

ARG os_type=ubuntu
RUN if [ "${os_type}" = "alpine" ] ; then apk update && apk add lcov bc --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ && rm -rf /var/cache/apk/* ; elif [ "${os_type}" = "ubuntu" ] ; then apt-get update && apt-get install -y lcov bc && apt-get clean ; fi

COPY . /code
WORKDIR /code

ARG make_procs=4

RUN cmake -DCMAKE_BUILD_TYPE=Debug . && make -j${make_procs}

# Entrypoint script:
COPY deps/starter-coverage-ut.sh /var

ENTRYPOINT ["sh", "/var/starter-coverage-ut.sh" ]

CMD []
