ARG base_tag=latest
FROM testillano/http2comm:${base_tag}
MAINTAINER testillano

LABEL testillano.h2agent_build.description="Docker image to build h2agent executable"

WORKDIR /code/build

ARG make_procs=4
ARG nlohmann_json_ver=v3.9.1
ARG pboettch_jsonschemavalidator_ver=2.1.0

RUN apk update && apk add \
    git

# nlohmann json
RUN set -x && \
    wget https://github.com/nlohmann/json/releases/download/${nlohmann_json_ver}/json.hpp && \
    mkdir /usr/local/include/nlohmann && mv json.hpp /usr/local/include/nlohmann && \
    set +x

# pboettch json-schema-validator
RUN set -x && \
    wget https://github.com/pboettch/json-schema-validator/archive/${pboettch_jsonschemavalidator_ver}.tar.gz && \
    tar xvf ${pboettch_jsonschemavalidator_ver}.tar.gz && cd json-schema-validator*/ && mkdir build && cd build && \
    cmake .. && make -j${make_procs} && make install && \
    cd .. && rm -rf * && \
    set +x

