ARG base_tag=latest
FROM ghcr.io/testillano/h2agent_builder:${base_tag}
LABEL maintainer="testillano"

LABEL testillano.h2agent.description="Docker image for h2agent UT coverage"

RUN apt-get update && apt-get install -y lcov bc && apt-get clean

COPY . /code
WORKDIR /code

ARG make_procs=4

RUN cmake -DCMAKE_BUILD_TYPE=Debug . && make -j${make_procs}

# Entrypoint script:
COPY deps/starter-coverage-ut.sh /var

ENTRYPOINT ["sh", "/var/starter-coverage-ut.sh" ]

CMD []
