ARG base_tag=latest
FROM ghcr.io/testillano/h2agent:${base_tag}
LABEL maintainer="testillano"

LABEL testillano.h2agent.description="Docker image for h2agent service for training"

COPY tools /home/h2agent/tools
COPY demo /home/h2agent/demo
COPY kata /home/h2agent/kata
WORKDIR /home/h2agent/

ARG enable_qa=false

# Installation
RUN apt-get update && apt-get install -y dos2unix netcat-openbsd && apt-get clean

## Installation for questions & answers (langchain & OpenAI)
RUN if [ "${enable_qa}" = "true" ] ; then apt-get update && apt-get install -y python3 python3-pip python3.12-venv && apt-get clean ; fi
RUN if [ "${enable_qa}" = "true" ] ; then python3 -m venv /opt/venv ; /bin/bash -c "source /opt/venv/bin/activate && pip3 install -r tools/questions-and-answers/requirements.txt" ; fi

RUN ln -s /opt/h2agent
RUN ln -s /opt/h2client
RUN ln -s /opt/matching-helper
RUN ln -s /opt/arashpartow-helper
RUN ln -s /opt/udp-server
RUN ln -s /opt/udp-client

ENTRYPOINT ["sleep", "infinity"]
CMD []
