ARG base_tag=latest
FROM ghcr.io/testillano/h2agent:${base_tag}
MAINTAINER testillano

LABEL testillano.h2agent.description="Docker image for h2agent service for training"

COPY tools /home/h2agent/tools
COPY demo /home/h2agent/demo
COPY kata /home/h2agent/kata
WORKDIR /home/h2agent/

ARG os_type=ubuntu
ARG enable_qa=false

# Update packages
RUN if [ "${os_type}" = "alpine" ] ; then apk update ; elif [ "${os_type}" = "ubuntu" ] ; then apt-get update ; fi

# Installation
RUN if [ "${os_type}" = "alpine" ] ; then apk add dos2unix ; elif [ "${os_type}" = "ubuntu" ] ; then apt-get install -y dos2unix netcat-openbsd ; fi

## Installation for questions & answers (langchain & OpenAI)
RUN if [ "${enable_qa}" = "true" -a "${os_type}" = "ubuntu" ] ; then apt-get install -y python3 python3-pip python3.12-venv ; fi
RUN if [ "${enable_qa}" = "true" -a "${os_type}" = "ubuntu" ] ; then python3 -m venv /opt/venv ; /bin/bash -c "source /opt/venv/bin/activate && pip3 install -r tools/questions-and-answers/requirements.txt" ; fi

# Cleanup
RUN if [ "${os_type}" = "alpine" ] ; then rm -rf /var/cache/apk/* ; elif [ "${os_type}" = "ubuntu" ] ; then apt-get clean ; fi

RUN ln -s /opt/h2agent
RUN ln -s /opt/h2client
RUN ln -s /opt/matching-helper
RUN ln -s /opt/arashpartow-helper
RUN ln -s /opt/udp-server
RUN ln -s /opt/udp-client

ENTRYPOINT ["sleep", "infinity"]
CMD []
