ARG base_tag=latest
FROM testillano/http2comm:${base_tag}
MAINTAINER testillano

LABEL testillano.h2agent_build.description="Docker image to build h2agent executable"

WORKDIR /code/build

ARG make_procs=4
ARG nlohmann_json_ver=v3.9.1
ARG pboettch_jsonschemavalidator_ver=2.1.0
ARG google_test_ver=v1.10.0
ARG jupp0r_prometheuscpp_ver=v0.12.3
ARG civetweb_civetweb_ver=v1.14

RUN apk update && apk add \
    git

# nlohmann json
RUN set -x && \
    wget https://github.com/nlohmann/json/releases/download/${nlohmann_json_ver}/json.hpp && \
    mkdir /usr/local/include/nlohmann && mv json.hpp /usr/local/include/nlohmann && \
    set +x

# pboettch json-schema-validator
RUN set -x && \
    wget https://github.com/pboettch/json-schema-validator/archive/${pboettch_jsonschemavalidator_ver}.tar.gz && \
    tar xvf ${pboettch_jsonschemavalidator_ver}.tar.gz && cd json-schema-validator*/ && mkdir build && cd build && \
    cmake .. && make -j${make_procs} && make install && \
    cd .. && rm -rf * && \
    set +x

# google test framework
RUN set -x && \
    wget https://github.com/google/googletest/archive/refs/tags/release-${google_test_ver:1}.tar.gz && \
    tar xvf release-${google_test_ver:1}.tar.gz && cd googletest-release*/ && cmake . && make -j${make_procs} install && \
    cd .. && rm -rf * && \
    set +x

# jupp0r prometheus-cpp
RUN apk add zlib-dev curl-dev
RUN set -x && \
    wget https://github.com/jupp0r/prometheus-cpp/archive/refs/tags/${jupp0r_prometheuscpp_ver}.tar.gz && \
    tar xvf ${jupp0r_prometheuscpp_ver}.tar.gz && cd prometheus-cpp*/3rdparty && \
    wget https://github.com/civetweb/civetweb/archive/refs/tags/${civetweb_civetweb_ver}.tar.gz && \
    tar xvf ${civetweb_civetweb_ver}.tar.gz && mv civetweb-*/* civetweb && cd .. && \
    mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DENABLE_PUSH=OFF -DENABLE_PULL=OFF .. && \
    make -j8 && make install && \
    cd .. && rm -rf * && \
    set +x

