ARG base_tag=latest
FROM ghcr.io/testillano/h2agent_builder:${base_tag}
LABEL maintainer="testillano"

LABEL testillano.h2agent.description="Docker image for h2agent CT coverage"

# nghttp2-proxy provides nghttpx (reverse proxy for HTTP/1.x access), used by
# starter.sh when H2AGENT_*_PROXY_PORT is set. Lost in the build refactor when
# the all-in-one "nghttp2" package was split to "nghttp2-client".
RUN apt-get update && apt-get install -y lcov bc curl jq nghttp2-client nghttp2-proxy netcat-openbsd socat && apt-get clean

COPY . /code
WORKDIR /code

ARG make_procs=4
RUN cmake -DCMAKE_BUILD_TYPE=Debug . && make -j${make_procs} h2agent

# Reuse starter.sh but point to Debug binary
RUN sed 's|/opt/h2agent|/code/build/Debug/bin/h2agent|g' deps/starter.sh > /var/starter.sh && chmod a+x /var/starter.sh

# Entrypoint script:
COPY deps/starter-coverage-ct.sh /var

ENTRYPOINT ["sh", "/var/starter-coverage-ct.sh" ]

CMD []
