{
 "title": "h2agent",
 "time": { "from": "2023-08-13T17:20:43.292Z", "to": "2023-08-13T17:22:33.318Z" },
 "templating": {
  "list": [
   {
    "name": "rate_interval",
    "query": "1s,15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "H2AGENT Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests received [traffic server]",
   "type": "timeseries",
   "description": "Accepted requests are all except: method not allowed, service unavailable, wrong api name or version.\n* processed request: could be provisioned or not",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(h2agent_traffic_server_observed_resquests_accepted_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} accepted {{method}}"
    },
    {
     "expr": "rate(h2agent_traffic_server_observed_resquests_errored_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} errored"
    },
    {
     "expr": "rate(h2agent_traffic_server_provisioned_requests_counter{result=\"successful\"}[$rate_interval]) > 0",
     "legendFormat": "{{source}} provisioned"
    },
    {
     "expr": "rate(h2agent_traffic_server_provisioned_requests_counter{result=\"failed\"}[$rate_interval]) > 0",
     "legendFormat": "{{source}} unprovisioned"
    }
   ]
  },
  {
   "title": "Responses sent [traffic server]",
   "type": "timeseries",
   "description": "Responses sent by the mock. Also series for purged contexts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(h2agent_traffic_server_observed_responses_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} {{method}} response [{{status_code}}]"
    },
    {
     "expr": "rate(h2agent_traffic_server_purged_contexts_counter{result=\"successful\"}[$rate_interval]) > 0",
     "legendFormat": "{{source}} purge {{result}}"
    },
    {
     "expr": "rate(h2agent_traffic_server_purged_contexts_counter{result=\"failed\"}[$rate_interval]) > 0",
     "legendFormat": "{{source}} purge {{result}}"
    }
   ]
  },
  {
   "title": "File system operations",
   "type": "timeseries",
   "description": "File system operations managed by the process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(h2agent_file_manager_operations_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "UDP socket operations",
   "type": "timeseries",
   "description": "UDP socket operations managed by the process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(h2agent_socket_manager_operations_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Responses delay gauge [traffic server]",
   "type": "gauge",
   "description": "h2agent traffic server: responses delays driven by mock.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(h2agent_traffic_server_responses_delay_seconds_gauge[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Response delay [traffic server]",
   "type": "timeseries",
   "description": "Response delay (latency)",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(h2agent_traffic_server_responses_delay_seconds_sum[$rate_interval]) / rate(h2agent_traffic_server_responses_delay_seconds_count[$rate_interval])",
     "legendFormat": "{{source}} latency"
    }
   ]
  },
  {
   "title": "Message sizes [traffic server]",
   "type": "gauge",
   "description": "h2agent traffic server: size for messages received and sent",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "h2agent_traffic_server_received_messages_size_bytes_gauge",
     "legendFormat": "receptions"
    },
    {
     "expr": "h2agent_traffic_server_sent_messages_size_bytes_gauge",
     "legendFormat": "transmissions"
    }
   ]
  },
  {
   "title": "UDP SERVER H2CLIENT Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests sent [traffic client]",
   "type": "timeseries",
   "description": "Requests sent by the client mock.\nUnsents (errors) are also visualized.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(udp_server_h2client_observed_resquests_sents_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} sent {{method}}"
    },
    {
     "expr": "rate(udp_server_h2client_observed_resquests_unsent_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} unsent {{method}}"
    }
   ]
  },
  {
   "title": "Responses received [traffic client]",
   "type": "timeseries",
   "description": "Requests sent by the client mock.\nTimeouts (errors) are also visualized.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(udp_server_h2client_observed_responses_received_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} {{method}} response [{{status_code}}]"
    },
    {
     "expr": "rate(udp_server_h2client_observed_responses_timedout_counter[$rate_interval]) > 0",
     "legendFormat": "{{source}} {{method}} timeout"
    }
   ]
  },
  {
   "title": "Responses delay gauge [traffic client]",
   "type": "gauge",
   "description": "udp-server-h2client traffic client: responses delays for the requests launched.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(udp_server_h2client_responses_delay_seconds_gauge[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Response delay [traffic client]",
   "type": "timeseries",
   "description": "Response delay (latency)",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(udp_server_h2client_responses_delay_seconds_sum[$rate_interval]) / rate(udp_server_h2client_responses_delay_seconds_count[$rate_interval])",
     "legendFormat": "{{source}} latency"
    }
   ]
  },
  {
   "title": "Message sizes [traffic client]",
   "type": "gauge",
   "description": "udp-server-h2client traffic client: size for messages received and sent",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "udp_server_h2client_received_messages_size_bytes_gauge",
     "legendFormat": "receptions"
    },
    {
     "expr": "udp_server_h2client_sent_messages_size_bytes_gauge\n",
     "legendFormat": "transmissions"
    }
   ]
  }
 ]
}