# Default values for h2agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  istio:
    sidecar:
      inject: false

name: h2agent

resources: {}
#  requests:
#    cpu: 20000m
#    memory: 10Mi
#  limits:
#    cpu: 3000m
#    memory: 100Mi

# command-line
h2agent_cl:
  log_level: Warning
  verbose:
    enabled: false
  #admin_port: 8074
  #traffic_server_port: 8000
  traffic_server_api_name: ""
  traffic_server_api_version: ""
  traffic_server_worker_threads: 1
  traffic_server_threads: 2
  traffic_server_key: ""
  traffic_server_crt: ""
  traffic_server_matching: ""
  traffic_server_provision: ""
  data:
    enabled: true
  data_key_history:
    enabled: true
  prometheus_response_delay_seconds_histogram_boundaries: ""
  prometheus_message_size_bytes_histogram_boundaries: ""
  metrics:
    enabled: true
  remote_servers_lazy_connection:
    enabled: false

utilsMountPath: "/opt/utils"

service:
  type: ClusterIP
  admin_port: 8074
  traffic_port: 8000
  prometheus_port: 8080

image:
  repository: ghcr.io/testillano/h2agent
  tag: latest
  pullPolicy: IfNotPresent

