# Default values for h2agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  istio:
    sidecar:
      inject: false

name: h2agent

resources: {}
#  requests:
#    cpu: 20000m
#    memory: 10Mi
#  limits:
#    cpu: 3000m
#    memory: 100Mi

# command-line
h2agent_cl:
  log_level: Warning
  verbose:
    enabled: false
  #admin_port: 8074
  #traffic_port: 8000
  server_api_name: app
  server_api_version: v1
  worker_threads: -1
  server_threads: 1
  server_key: ""
  server_crt: ""
  server_request_schema: ""

service:
  type: ClusterIP
  admin_port: 8074
  traffic_port: 8000

image:
  repository: testillano/h2agent
  tag: latest
  pullPolicy: IfNotPresent

