global:
  scrape_interval: 5s
  external_labels:
    monitor: 'h2agent'

scrape_configs:
  - job_name: 'h2agent'
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
