apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "h2agent.name" . }}
  labels:
    {{- include "h2agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "h2agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "h2agent.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.global.istio.sidecar.inject | default false | quote }}
    spec:
      {{- if .Values.utilsMountPath }}
      volumes:
        - name: {{ include "h2agent.name" . }}-helper-functions-cfg-vol
          configMap:
            name: {{ include "h2agent.name" . | lower | replace "_" "-" }}-helpers-config
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.utilsMountPath }}
          volumeMounts:
            - name: {{ include "h2agent.name" . }}-helper-functions-cfg-vol
              mountPath: {{ .Values.utilsMountPath }}
          {{- end }}
          args:
            - "--log-level"
            - {{ .Values.h2agent_cl.log_level | quote }}
            {{- if .Values.h2agent_cl.verbose.enabled }}
            - "--verbose"
            {{- end }}
            - "--admin-port"
            - {{ .Values.service.admin_port | quote }}
            - "--traffic-server-port"
            - {{ .Values.service.traffic_port | quote }}
            - "--traffic-server-api-name"
            - {{ .Values.h2agent_cl.traffic_server_api_name | quote }}
            - "--traffic-server-api-version"
            - {{ .Values.h2agent_cl.traffic_server_api_version | quote }}
            - "--traffic-server-worker-threads"
            - {{ .Values.h2agent_cl.traffic_server_worker_threads | quote }}
            {{- if ne .Values.h2agent_cl.traffic_server_key ""  }}
            - "--traffic-server-key"
            - {{ .Values.h2agent_cl.traffic_server_key | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.traffic_server_crt ""  }}
            - "--traffic-server-crt"
            - {{ .Values.h2agent_cl.traffic_server_crt | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.traffic_server_matching ""  }}
            - "--traffic-server-matching"
            - {{ .Values.h2agent_cl.traffic_server_matching | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.traffic_server_provision ""  }}
            - "--traffic-server-provision"
            - {{ .Values.h2agent_cl.traffic_server_provision | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.schema ""  }}
            - "--schema"
            - {{ .Values.h2agent_cl.schema | quote }}
            {{- end }}
            {{- if not .Values.h2agent_cl.data.enabled }}
            - "--discard-data"
            {{- end }}
            {{- if not .Values.h2agent_cl.data_key_history.enabled }}
            - "--discard-data-key-history"
            {{- end }}
            - "--prometheus-port"
            - {{ .Values.service.prometheus_port | quote }}
            {{- if ne .Values.h2agent_cl.prometheus_response_delay_seconds_histogram_boundaries "" }}
            - "--prometheus-response-delay-seconds-histogram-boundaries"
            - {{ .Values.h2agent_cl.prometheus_response_delay_seconds_histogram_boundaries | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.prometheus_message_size_bytes_histogram_boundaries "" }}
            - "--prometheus-message-size-bytes-histogram-boundaries"
            - {{ .Values.h2agent_cl.prometheus_message_size_bytes_histogram_boundaries | quote }}
            {{- end }}
            {{- if not .Values.h2agent_cl.metrics.enabled }}
            - "--disable-metrics"
            {{- end }}
            {{- if .Values.h2agent_cl.remote_servers_lazy_connection.enabled }}
            - "--remote-servers-lazy-connection"
            {{- end }}

          # livenessProbe & readinessProbe look for admin port, as main app is
          #  blocking on startup and will restart the container in case of crash.
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.traffic_port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            #httpGet:
            #  path: /healthz
            #  port: {{ .Values.service.admin_port }}
            tcpSocket:
              port: {{ .Values.service.admin_port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo source '{{ .Values.utilsMountPath }}/helpers.src' >> ~/.bashrc"]
