apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "h2agent.name" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    helm.sh/chart: {{ template "h2agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "h2agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "h2agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.global.istio.sidecar.inject | default false | quote }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - "--log-level"
            - {{ .Values.h2agent_cl.log_level | quote }}
            {{- if .Values.h2agent_cl.verbose.enabled }}
            - "--verbose"
            {{- end }}
            - "--admin-port"
            - {{ .Values.service.admin_port | quote }}
            - "--server-port"
            - {{ .Values.service.traffic_port | quote }}
            - "--server-api-name"
            - {{ .Values.h2agent_cl.server_api_name | quote }}
            - "--server-api-version"
            - {{ .Values.h2agent_cl.server_api_version | quote }}
            - "--worker-threads"
            - {{ .Values.h2agent_cl.worker_threads | quote }}
            - "--server-threads"
            - {{ .Values.h2agent_cl.server_threads | quote }}
            {{- if ne .Values.h2agent_cl.server_key ""  }}
            - "--server-key"
            - {{ .Values.h2agent_cl.server_key | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.server_crt ""  }}
            - "--server-crt"
            - {{ .Values.h2agent_cl.server_crt | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.server_request_schema ""  }}
            - "--server-request-schema"
            - {{ .Values.h2agent_cl.server_request_schema | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.server_matching ""  }}
            - "--server-matching"
            - {{ .Values.h2agent_cl.server_matching | quote }}
            {{- end }}
            {{- if ne .Values.h2agent_cl.server_provision ""  }}
            - "--server-provision"
            - {{ .Values.h2agent_cl.server_provision | quote }}
            {{- end }}
            {{- if not .Values.h2agent_cl.server_data.enabled }}
            - "--disable-server-data"
            {{- end }}
            {{- if not .Values.h2agent_cl.server_data_requests_history.enabled }}
            - "--disable-server-data-requests-history"
            {{- end }}

