apiVersion: v1
kind: ConfigMap
metadata:
  name: {{  include "h2agent.name" . | lower | replace "_" "-" }}-helpers-config
  labels:
{{ include "h2agent.labels" . | indent 4 }}
data:
{{ (.Files.Glob "native-helpers.src").AsConfig | indent 2 }}

  helpers.src: |
    #!/bin/echo "source me!"

    #######################
    # VARIABLES FROM HELM #
    #######################
    PNAME="{{ .Values.name }}"
    TRAFFIC_URL="http://localhost:{{ .Values.service.traffic_port }}"
    METRICS_URL="http://localhost:{{ .Values.service.prometheus_port }}/metrics"
    SERVER_API="{{ .Values.h2agent_cl.traffic_server_api_name }}/{{ .Values.h2agent_cl.traffic_server_api_version }}"
    ADMIN_URL="http://localhost:{{ .Values.service.admin_port }}/admin/v1"
    CURL="curl -i --http2-prior-knowledge"

    #############
    # EXECUTION #
    #############

    # Source native helpers:
    source "{{ .Values.utilsMountPath }}/native-helpers.src"

