apiVersion: v1
kind: ConfigMap
metadata:
  name: {{  include "h2agent.name" . | lower | replace "_" "-" }}-helpers-config
  labels:
{{ include "h2agent.labels" . | indent 4 }}
data:
{{ (.Files.Glob "native-helpers.bash").AsConfig | indent 2 }}

  helpers.bash: |
    #!/bin/echo "source me!"

    #######################
    # VARIABLES FROM HELM #
    #######################
    PNAME="{{ .Values.name }}"
    TRAFFIC_PORT="{{ .Values.service.traffic_port }}"
    TRAFFIC_SERVER_API="{{ .Values.h2agent_cl.traffic_server_api_name }}/{{ .Values.h2agent_cl.traffic_server_api_version }}"
    ADMIN_PORT="{{ .Values.service.admin_port }}"
    METRICS_PORT="{{ .Values.service.prometheus_port }}"
    CURL=${CURL:-"curl -i --http2-prior-knowledge"} # may be just --http2, --http1.0, --http1.1, or nothing

    #############
    # EXECUTION #
    #############

    # Source native helpers:
    source "{{ .Values.utilsMountPath }}/native-helpers.bash"

