apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2agent.name" . }}
  labels:
    {{- include "h2agent.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: metrics
    prometheus.io/port: {{ .Values.service.prometheus_port | quote }}
    prometheus.io/scrape: {{ .Values.h2agent_cl.metrics.enabled | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.admin_port }}
      targetPort: {{ .Values.service.admin_port }}
      protocol: TCP
      name: http2-admin
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.admin_nodePort }}
      {{- end }}
    - port: {{ .Values.service.traffic_port }}
      targetPort: {{ .Values.service.traffic_port }}
      protocol: TCP
      name: http2-traffic
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.traffic_nodePort }}
      {{- end }}
    {{- if .Values.h2agent_cl.metrics.enabled }}
    - port: {{ .Values.service.prometheus_port }}
      targetPort: {{ .Values.service.prometheus_port }}
      protocol: TCP
      name: http-metrics
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.prometheus_nodePort }}
      {{- end }}
    {{- end }}
    # HTTP/1 proxy
    {{- if .Values.service.traffic_http1_port | default false }}
    - port: {{ .Values.service.traffic_http1_port }}
      targetPort: {{ .Values.service.traffic_http1_port }}
      protocol: TCP
      name: http1-traffic
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.traffic_http1_nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "h2agent.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
