apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2agent.name" . }}
  labels:
    {{- include "h2agent.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: metrics
    prometheus.io/port: {{ .Values.service.prometheus_port | quote }}
    prometheus.io/scrape: {{ .Values.h2agent_cl.metrics.enabled | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.admin_port }}
      targetPort: {{ .Values.service.admin_port }}
      protocol: TCP
      name: http2-admin
    - port: {{ .Values.service.traffic_port }}
      targetPort: {{ .Values.service.traffic_port }}
      protocol: TCP
      name: http2-traffic
    {{- if .Values.h2agent_cl.metrics.enabled }}
    - port: {{ .Values.service.prometheus_port }}
      targetPort: {{ .Values.service.prometheus_port }}
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "h2agent.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
