apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2agent.name" . }}
  labels:
    {{- include "h2agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.admin_port }}
      targetPort: {{ .Values.service.admin_port }}
      protocol: TCP
      name: http2-admin
    - port: {{ .Values.service.traffic_port }}
      targetPort: {{ .Values.service.traffic_port }}
      protocol: TCP
      name: http2-traffic
  selector:
    {{- include "h2agent.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
